################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
  - &org0
    Name: org0
    ID: org0MSP
    MSPDir: /tmp/hyperledger/org0/admin/msp

    Policies:
      Readers:
        Type: Signature
        Rule: "OR('org0MSP.member', 'org1MSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('org0MSP.member', 'org1MSP.member')"
      Admins:
        Type: Signature
        Rule: "AND('org0MSP.admin', 'org1MSP.admin')"

  - &org1
    Name: org1
    ID: org1MSP
    MSPDir: /tmp/hyperledger/org1/admin/msp

    Policies:
      Readers:
        Type: Signature
        Rule: "OR('org0MSP.member', 'org1MSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('org0MSP.member', 'org1MSP.member')"
      Admins:
        Type: Signature
        Rule: "AND('org0MSP.admin', 'org1MSP.admin')"

    AnchorPeers:
      - Host: peer1-org1
        Port: 7051

################################################################################
#
#   CHANNEL
#
#   This section defines the values to encode into a config transaction or
#   genesis block for channel related parameters.
#
################################################################################
Channel: &ChannelDefaults
  # Policies defines the set of policies at this level of the config tree
  # For Channel policies, their canonical path is
  #   /Channel/<PolicyName>
  Policies:
    # Who may invoke the 'Deliver' API
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    # Who may invoke the 'Broadcast' API
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    # By default, who may modify elements at this config level
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"


################################################################################
#
#   SECTION: Application
#
################################################################################
Application: &ApplicationDefaults
  # Organizations is the list of orgs which are defined as participants on
  # the application side of the network
  Organizations:
  # Policies defines the set of policies at this level of the config tree
  # For Application policies, their canonical path is
  #   /Channel/Application/<PolicyName>
  Policies: &ApplicationDefaultPolicies
    LifecycleEndorsement:
      Type: Signature
      Rule: "OR('org0MSP.member', 'org1MSP.member')"
    Endorsement:
      Type: Signature
      Rule: "OR('org0MSP.member', 'org1MSP.member')"
    Readers:
      Type: Signature
      Rule: "OR('org0MSP.member', 'org1MSP.member')"
    Writers:
      Type: Signature
      Rule: "OR('org0MSP.member', 'org1MSP.member')"
    Admins:
      Type: Signature
      Rule: "OR('org0MSP.member', 'org1MSP.member')"

################################################################################
#
#   SECTION: Profiles
#
################################################################################
Profiles:
  OrgsOrdererGenesis:
    Orderer:
      OrdererType: solo
      Addresses:
        - orderer1-org0:7050

      BatchTimeout: 2s

      BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB

      Policies:
        Readers:
          Type: Signature
          Rule: "OR('org0MSP.member', 'org1MSP.member')"
        Writers:
          Type: Signature
          Rule: "OR('org0MSP.member', 'org1MSP.member')"
        Admins:
          Type: Signature
          Rule: "AND('org0MSP.admin', 'org1MSP.admin')"
        BlockValidation:
          Type: Signature
          Rule: "OR('org0MSP.member')"

      Organizations:
        - *org0

    Policies:
      Readers:
        Type: Signature
        Rule: "OR('org0MSP.member', 'org1MSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('org0MSP.member', 'org1MSP.member')"
      Admins:
        Type: Signature
        Rule: "AND('org0MSP.admin', 'org1MSP.admin')"

    Consortiums:
      SampleConsortium:
        Organizations:
          - *org1

  OrgsChannel:
    <<: *ChannelDefaults
    Consortium: SampleConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - <<: *org1
