Organizations:
  - &Org1MSP
    Name: Org1MSP

    ID: Org1MSP

    MSPDir: ./organizations/peerOrganizations/org1.example.com/msp

    Policies:
      Readers:
        Type: Signature
        Rule: "OR('Org1MSP.admin' , 'Org1MSP.peer' , 'Org1MSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('Org1MSP.admin' , 'Org1MSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('Org1MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('Org1MSP.peer')"

Organizations:
  - &OrdererOrg
    Name: OrdererOrg

    ID: OrdererMSP

    MSPDir: ./organizations/ordererOrganizations/orderer.example.com/msp

    OrdererEndpoints:
      - orderer.orderer.example.com:14132

    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.admin')"


Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true
    # V1_4: true
  
  Orderer: &OrdererCapabilities
    V2_0: true
    # V1_4: true

  Application: &ApplicationCapabilities
    V2_0: true
    # V1_4: true 

Application: &ApplicationDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"

  Capabilities:
    <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
  OrdererType: etcdraft
  
  Addresses: 
    - orderer.orderer.example.com:14132

  EtcdRaft:
    Consenters:
      - Host: orderer.orderer.example.com
        Port: 14132
        ClientTLSCert: ./organizations/ordererOrganizations/orderer.example.com/orderers/orderer.orderer.example.com/tls/server.crt
        ServerTLSCert: ./organizations/ordererOrganizations/orderer.example.com/orderers/orderer.orderer.example.com/tls/server.crt

  BatchTimeout: 999ms

  BatchSize:
    MaxMessageCount: 1000
    AbsoluteMaxBytes: 99MB
    PreferredMaxBytes: 10MB

  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"

    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"

  Capabilities:
    <<: *OrdererCapabilities

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"

  Capabilities:
    <<: *ChannelCapabilities

Profiles:
  mainchannel:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
    Consortium: SampleConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *Org1MSP
    Capabilities:
      <<: *ChannelCapabilities

  OrdererGenesis:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
    Consortiums:
      SampleConsortium:
        Organizations:
          - *Org1MSP
    Capabilities:
      <<: *ChannelCapabilities
