PeerOrgs:
  - Name: Org1
    Domain: org1.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - peer1.org1.example.com

    Users:
      Count: 1

OrdererOrgs:
  - Name: Orderer
    Domain: orderer.example.com
    EnableNodeOUs: true

    Specs:
      - Hostname: orderer
        SANS:
          - orderer.orderer.example.com
        