services:
  couchdb-base:
    image: couchdb:3.1.1
    environment: 
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "9984:5984"

  # peer-couch-base:
  #   extends: couchdb-base
  #   environment:
  #     - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
  #     - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb4:5984
  #     - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
  #     - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
  #   depends_on:
  #     - couchdb-base



########### configuration ############
  peer0.org1.example.com:
    container_name: peer0.org1.example.com
    extends:
      file: $PWD/docker/common/peer-base.yaml
      service: peer-base
    environment:
      # Peer specific variables
      - CORE_PEER_ID=peer0.org1.example.com
      - CORE_PEER_ADDRESS=peer0.org1.example.com:11132
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11132
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.example.com:11134
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11134
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.example.com:11132
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.example.com:11132
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_test
      - GRPC_VERBOSITY=debug
      - CORE_OPERATIONS_LISTENADDRESS=peer0.org1.example.com:11136
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - $PWD/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp:/var/hyperledger/fabric/msp
      - $PWD/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls:/var/hyperledger/fabric/tls
      - peer0.org1.example.com:/var/hyperledger/production
    ports:
      - 11132:11132
      - 11136:11136
    networks:
      - docker_network_name

  orderer.example.com:
    container_name: orderer.example.com
    extends:
      file: $PWD/docker/common/orderer-base.yaml
      service: orderer-base
    environment:
      - ORDERER_GENERAL_LISTENPORT=14132
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer.example.com:9443
      - GRPC_VERBOSITY=debug
    volumes:
      - $PWD/channel-artifacts:/var/hyperledger/orderer
      - $PWD/organizations/ordererOrganizations/orderer.example.com/orderers/orderer.orderer.example.com/msp:/var/hyperledger/orderer/msp
      - $PWD/organizations/ordererOrganizations/orderer.example.com/orderers/orderer.orderer.example.com/tls:/var/hyperledger/orderer/tls
      - orderer.example.com:/var/hyperledger/production/orderer
    depends_on:
      - ca.org1.example.com
      # - ca.org2.example.com
      # - ca.org3.example.com
      # - ca.org4.example.com
    ports:
      - 14132:14132
      - 9443:9443
    networks:
      - docker_network_name

  ca.org1.example.com:
    container_name: ca.org1.example.com
    extends:
      file: $PWD/docker/common/ca-base.yaml
      service: ca-base
    environment:
      - FABRIC_CA_SERVER_CA_NAME=ca.org1.example.com
      - FABRIC_CA_SERVER_PORT=11135
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk 
    ports:
      - "11135:11135"
    volumes:
      - $PWD/fabric-ca/org1.example.com:/etc/hyperledger/fabric-ca-server
      - $PWD/organizations/peerOrganizations/org1.example.com/ca:/etc/hyperledger/fabric-ca-server-config
    networks:
      - docker_network_name

  cli.org1.example.com:
    container_name: cli.org1.example.com
    extends:
      file: $PWD/docker/common/cli-base.yaml
      service: cli-base
    environment:
      CORE_PEER_ID=cli
      CORE_PEER_ADDRESS=peer0.org1.example.com:11132
      CORE_PEER_LOCALMSPID=Org1MSP
      CORE_PEER_TLS_ENABLED=true
      CORE_PEER_TLS_CERT_FILE=/path/to/crypto-config/peer/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
      CORE_PEER_TLS_KEY_FILE=/path/to/crypto-config/peer/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.key
      CORE_PEER_TLS_ROOTCERT_FILE=/path/to/crypto-config/peer/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
      CORE_PEER_MSPCONFIGPATH=/path/to/crypto-config/peer/organizations/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
    volumes:
      - /var/run/:/host/var/run/
      - $PWD/blockchain/gen/organizations:/path/to/crypto-config/peer/organizations/
      - $PWD/blockchain/scripts/container:/path/to/crypto-config/peer/scripts/
      - $PWD/blockchain/gen/channel-artifacts:/path/to/crypto-config/peer/channel-artifacts/
      - $PWD/blockchain/contracts:/usr/local/go/src/
    depends_on:
      - orderer.example.com
      # - peer0.id1.local.healthchain.com
      # - peer0.id2.local.healthchain.com
      # - peer0.id1.state.healthchain.com
      - peer0.org1.example.com
    networks:
      - docker_network_name

volumes:
  peer0.org1.example.com:
  orderer.example.com:
  ca.org1.example.com:
  cli.org1.example.com:


networks:
  docker_network_name:
